from tkinter import *
from tkinter import ttk
from PIL import ImageTk
from PIL import Image as Img
from pyperclip import copy
from pylatex import Document, Alignat


class Abc:
    def __init__(self):
        self.root = Tk()
        self.root.geometry('732x400')
        self.root.title('Оформление математических формул')
        self.root.config(bg='#202020')

        self.tablet = ttk.Notebook(self.root)
        self.a_tab = ttk.Frame(self.tablet)
        self.b_tab = ttk.Frame(self.tablet)
        self.c_tab = ttk.Frame(self.tablet)
        self.d_tab = ttk.Frame(self.tablet)
        self.e_tab = ttk.Frame(self.tablet)
        self.f_tab = ttk.Frame(self.tablet)
        self.tablet.add(self.a_tab, text="Math")
        self.tablet.add(self.b_tab, text="Greek")
        self.tablet.add(self.c_tab, text="Relations")
        self.tablet.add(self.d_tab, text="Logic")
        self.tablet.add(self.e_tab, text="Symbols")
        self.tablet.add(self.f_tab, text="Arrows")
        self.tablet.place(x=20, y=20, width=692, height=110)
        self.buttons()
        self.textbox = Text(self.root, relief=FLAT)
        self.textbox.place(x=20, y=142, width=692, height=170)
        self.img_clr = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((593, 1, 609, 17)))
        self.img_cpy = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((593, 18, 609, 34)))
        self.img_pdf = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((593, 35, 609, 51)))
        self.img_nxt = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((593, 52, 609, 68)))
        Button(self.root, image=self.img_clr, command=lambda: self.textbox.delete(0.0, END)).place(x=20, y=313)
        Button(self.root, image=self.img_cpy, command=lambda: copy(self.textbox.get(0.0, END))).place(x=44, y=313)
        Button(self.root, image=self.img_pdf, command=self.transform).place(x=68, y=313)
        Button(self.root, image=self.img_nxt, command=lambda: self.textbox.insert(END, r'%\newline%')).place(x=92, y=313)
        self.root.mainloop()

    def buttons(self):
        self.i1_1 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((1, 1, 37, 37)))
        Button(self.a_tab, image=self.i1_1, command=lambda: self.textbox.insert(END, r' \widetilde{ab} ')).place(x=2, y=2, width=40, height=40)
        self.i1_2 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((38, 1, 74, 37)))
        Button(self.a_tab, image=self.i1_2, command=lambda: self.textbox.insert(END, r' \widetilde{ab} ')).place(x=45, y=2, width=40, height=40)
        self.i1_3 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((75, 1, 111, 37)))
        Button(self.a_tab, image=self.i1_3, command=lambda: self.textbox.insert(END, r' \overline{ab} ')).place(x=88, y=2, width=40, height=40)
        self.i1_4 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((112, 1, 148, 37)))
        Button(self.a_tab, image=self.i1_4, command=lambda: self.textbox.insert(END, r' \overbrace{ab} ')).place(x=131, y=2, width=40, height=40)
        self.i1_5 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((149, 1, 185, 37)))
        Button(self.a_tab, image=self.i1_5, command=lambda: self.textbox.insert(END, r' \sqrt{ab} ')).place(x=174, y=2, width=40, height=40)
        self.i1_6 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((186, 1, 222, 37)))
        Button(self.a_tab, image=self.i1_6, command=lambda: self.textbox.insert(END, r" f' ")).place(x=217, y=2, width=40, height=40)
        self.i1_7 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((223, 1, 259, 37)))
        Button(self.a_tab, image=self.i1_7, command=lambda: self.textbox.insert(END, r' x^{k} ')).place(x=260, y=2, width=40, height=40)
        self.i1_8 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((260, 1, 296, 37)))
        Button(self.a_tab, image=self.i1_8, command=lambda: self.textbox.insert(END, r' \lim_{a \rightarrow b} ')).place(x=303, y=2, width=40, height=40)
        self.i1_9 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((297, 1, 333, 37)))
        Button(self.a_tab, image=self.i1_9, command=lambda: self.textbox.insert(END, r' \begin{bmatrix}a & b \\c & d \end{bmatrix} ')).place(x=346, y=2, width=40, height=40)
        self.i1_10 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((334, 1, 370, 37)))
        Button(self.a_tab, image=self.i1_10, command=lambda: self.textbox.insert(END, r' \big(a\big) ')).place(x=389, y=2, width=40, height=40)
        self.i1_11 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((371, 1, 407, 37)))
        Button(self.a_tab, image=self.i1_11, command=lambda: self.textbox.insert(END, r' \int_a^b x ')).place(x=432, y=2, width=40, height=40)
        self.i1_12 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((408, 1, 444, 37)))
        Button(self.a_tab, image=self.i1_12, command=lambda: self.textbox.insert(END, r' \sum_a^b x ')).place(x=475, y=2, width=40, height=40)
        self.i1_13 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((445, 1, 481, 37)))
        Button(self.a_tab, image=self.i1_13, command=lambda: self.textbox.insert(END, r' \prod_a^b x ')).place(x=518, y=2, width=40, height=40)
        self.i1_14 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((482, 1, 518, 37)))
        Button(self.a_tab, image=self.i1_14, command=lambda: self.textbox.insert(END, r' \bigcap_a^b x ')).place(x=561, y=2, width=40, height=40)
        self.i1_15 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((519, 1, 555, 37)))
        Button(self.a_tab, image=self.i1_15, command=lambda: self.textbox.insert(END, r' \bigvee_a^b x ')).place(x=604, y=2, width=40, height=40)
        self.i1_16 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((556, 1, 589, 37)))
        Button(self.a_tab, image=self.i1_16, command=lambda: self.textbox.insert(END, r' \bigotimes ')).place(x=647, y=2, width=40, height=40)

        self.i2_1 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((1, 38, 37, 74)))
        Button(self.a_tab, image=self.i2_1, command=lambda: self.textbox.insert(END, r' \widehat{ab} ')).place(x=2, y=45, width=40, height=40)
        self.i2_2 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((38, 38, 74, 74)))
        Button(self.a_tab, image=self.i2_2, command=lambda: self.textbox.insert(END, r' \overrightarrow{ab} ')).place(x=45, y=45, width=40, height=40)
        self.i2_3 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((75, 38, 111, 74)))
        Button(self.a_tab, image=self.i2_3, command=lambda: self.textbox.insert(END, r' \underline{ab} ')).place(x=88, y=45, width=40, height=40)
        self.i2_4 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((112, 38, 148, 74)))
        Button(self.a_tab, image=self.i2_4, command=lambda: self.textbox.insert(END, r' \underbrace{ab} ')).place(x=131, y=45, width=40, height=40)
        self.i2_5 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((149, 38, 185, 74)))
        Button(self.a_tab, image=self.i2_5, command=lambda: self.textbox.insert(END, r' \sqrt[n]{ab} ')).place(x=174, y=45, width=40, height=40)
        self.i2_6 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((186, 38, 222, 74)))
        Button(self.a_tab, image=self.i2_6, command=lambda: self.textbox.insert(END, r' \frac{a}{b} ')).place(x=217, y=45, width=40, height=40)
        self.i2_7 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((223, 38, 259, 74)))
        Button(self.a_tab, image=self.i2_7, command=lambda: self.textbox.insert(END, r' x_{k} ')).place(x=260, y=45, width=40, height=40)
        self.i2_8 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((260, 38, 296, 74)))
        Button(self.a_tab, image=self.i2_8, command=lambda: self.textbox.insert(END, r' \frac{\partial^nf}{\partial x^n} ')).place(x=303, y=45, width=40, height=40)
        self.i2_9 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((297, 38, 333, 74)))
        Button(self.a_tab, image=self.i2_9, command=lambda: self.textbox.insert(END, r' x =\begin{cases}a & x = 0\\b & x > 0\end{cases} ')).place(x=346, y=45, width=40, height=40)
        self.i2_10 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((334, 38, 370, 74)))
        Button(self.a_tab, image=self.i2_10, command=lambda: self.textbox.insert(END, r' \big\{a\big\} ')).place(x=389, y=45, width=40, height=40)
        self.i2_11 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((371, 38, 407, 74)))
        Button(self.a_tab, image=self.i2_11, command=lambda: self.textbox.insert(END, r' \oint_a^b x ')).place(x=432, y=45, width=40, height=40)
        self.i2_12 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((408, 38, 444, 74)))
        Button(self.a_tab, image=self.i2_12, command=lambda: self.textbox.insert(END, r' \bigsqcup_a^b x ')).place(x=475, y=45, width=40, height=40)
        self.i2_13 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((445, 38, 481, 74)))
        Button(self.a_tab, image=self.i2_13, command=lambda: self.textbox.insert(END, r' \coprod_a^b x ')).place(x=518, y=45, width=40, height=40)
        self.i2_14 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((482, 38, 518, 74)))
        Button(self.a_tab, image=self.i2_14, command=lambda: self.textbox.insert(END, r' \bigcup_a^b x ')).place(x=561, y=45, width=40, height=40)
        self.i2_15 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((519, 38, 555, 74)))
        Button(self.a_tab, image=self.i2_15, command=lambda: self.textbox.insert(END, r' \bigwedge_a^b x ')).place(x=604, y=45, width=40, height=40)
        self.i2_16 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((556, 38, 589, 74)))
        Button(self.a_tab, image=self.i2_16, command=lambda: self.textbox.insert(END, r' \bigoplus ')).place(x=647, y=45, width=40, height=40)


        self.i3_1 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((1, 75, 25, 99)))
        Button(self.b_tab, image=self.i3_1, command=lambda: self.textbox.insert(END, r' \alpha ')).place(x=2, y=2, width=26, height=26)
        self.i3_2 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((26, 75, 50, 99)))
        Button(self.b_tab, image=self.i3_2, command=lambda: self.textbox.insert(END, r' \beta ')).place(x=31, y=2, width=26, height=26)
        self.i3_3 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((51, 75, 75, 99)))
        Button(self.b_tab, image=self.i3_3, command=lambda: self.textbox.insert(END, r' \gamma ')).place(x=88, y=2, width=26, height=26)
        self.i3_4 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((76, 75, 100, 99)))
        Button(self.b_tab, image=self.i3_4, command=lambda: self.textbox.insert(END, r' \delta ')).place(x=131, y=2, width=26, height=26)
        self.i3_5 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((101, 75, 125, 99)))
        Button(self.b_tab, image=self.i3_5, command=lambda: self.textbox.insert(END, r' \epsilon ')).place(x=174, y=2, width=26, height=26)
        self.i3_6 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((126, 75, 150, 99)))
        Button(self.b_tab, image=self.i3_6, command=lambda: self.textbox.insert(END, r' \varepsilon ')).place(x=217, y=2, width=26, height=26)
        self.i3_7 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((151, 75, 175, 99)))
        Button(self.b_tab, image=self.i3_7, command=lambda: self.textbox.insert(END, r' \zeta ')).place(x=260, y=2, width=26, height=26)
        self.i3_8 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((176, 75, 200, 99)))
        Button(self.b_tab, image=self.i3_8, command=lambda: self.textbox.insert(END, r' \eta ')).place(x=303, y=2, width=26, height=26)
        self.i3_9 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((201, 75, 225, 99)))
        Button(self.b_tab, image=self.i3_9, command=lambda: self.textbox.insert(END, r' \theta ')).place(x=346, y=2, width=26, height=26)
        self.i3_10 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((226, 75, 250, 99)))
        Button(self.b_tab, image=self.i3_10, command=lambda: self.textbox.insert(END, r' \vartheta ')).place(x=389, y=2, width=26, height=26)
        self.i3_11 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((251, 75, 275, 99)))
        Button(self.b_tab, image=self.i3_11, command=lambda: self.textbox.insert(END, r' \gamma ')).place(x=432, y=2, width=26, height=26)
        self.i3_12 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((276, 75, 300, 99)))
        Button(self.b_tab, image=self.i3_12, command=lambda: self.textbox.insert(END, r' \kappa ')).place(x=475, y=2, width=26, height=26)
        self.i3_13 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((301, 75, 325, 99)))
        Button(self.b_tab, image=self.i3_13, command=lambda: self.textbox.insert(END, r' \lambda ')).place(x=518, y=2, width=26, height=26)
        self.i3_14 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((326, 75, 350, 99)))
        Button(self.b_tab, image=self.i3_14, command=lambda: self.textbox.insert(END, r' \mu ')).place(x=561, y=2, width=26, height=26)
        self.i3_15 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((351, 75, 375, 99)))
        Button(self.b_tab, image=self.i3_15, command=lambda: self.textbox.insert(END, r' \nu ')).place(x=604, y=2, width=26, height=26)
        self.i3_16 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((376, 75, 400, 99)))
        Button(self.b_tab, image=self.i3_16, command=lambda: self.textbox.insert(END, r' \Gamma ')).place(x=647, y=2, width=26, height=26)

        self.i4_1 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((1, 100, 25, 124)))
        Button(self.b_tab, image=self.i4_1, command=lambda: self.textbox.insert(END, r' \widehat{ab} ')).place(x=2, y=45, width=26, height=26)
        self.i4_2 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((26, 100, 50, 124)))
        Button(self.b_tab, image=self.i4_2, command=lambda: self.textbox.insert(END, r' \overrightarrow{ab} ')).place(x=45, y=45, width=26, height=26)
        self.i4_3 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((51, 100, 75, 124)))
        Button(self.b_tab, image=self.i4_3, command=lambda: self.textbox.insert(END, r' \underline{ab} ')).place(x=88, y=45, width=26, height=26)
        self.i4_4 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((76, 100, 100, 124)))
        Button(self.b_tab, image=self.i4_4, command=lambda: self.textbox.insert(END, r' \underbrace{ab} ')).place(x=131, y=45, width=26, height=26)
        self.i4_5 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((101, 100, 125, 124)))
        Button(self.b_tab, image=self.i4_5, command=lambda: self.textbox.insert(END, r' \sqrt[n]{ab} ')).place(x=174, y=45, width=26, height=26)
        self.i4_6 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((126, 100, 150, 124)))
        Button(self.b_tab, image=self.i4_6, command=lambda: self.textbox.insert(END, r' \frac{a}{b} ')).place(x=217, y=45, width=26, height=26)
        self.i4_7 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((151, 100, 175, 124)))
        Button(self.b_tab, image=self.i4_7, command=lambda: self.textbox.insert(END, r' x_{k} ')).place(x=260, y=45, width=26, height=26)
        self.i4_8 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((176, 100, 200, 124)))
        Button(self.b_tab, image=self.i4_8, command=lambda: self.textbox.insert(END, r' \frac{\partial^nf}{\partial x^n} ')).place(x=303, y=45, width=26, height=26)
        self.i4_9 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((201, 100, 225, 124)))
        Button(self.b_tab, image=self.i4_9, command=lambda: self.textbox.insert(END, r' x =\begin{cases}a & x = 0\\b & x > 0\end{cases} ')).place(x=346, y=45, width=26, height=26)
        self.i4_10 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((226, 100, 250, 124)))
        Button(self.b_tab, image=self.i4_10, command=lambda: self.textbox.insert(END, r' \big\{a\big\} ')).place(x=389, y=45, width=26, height=26)
        self.i4_11 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((251, 100, 275, 124)))
        Button(self.b_tab, image=self.i4_11, command=lambda: self.textbox.insert(END, r' \oint_a^b x ')).place(x=432, y=45, width=26, height=26)
        self.i4_12 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((276, 100, 300, 124)))
        Button(self.b_tab, image=self.i4_12, command=lambda: self.textbox.insert(END, r' \bigsqcup_a^b x ')).place(x=475, y=45, width=26, height=26)
        self.i4_13 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((301, 100, 325, 124)))
        Button(self.b_tab, image=self.i4_13, command=lambda: self.textbox.insert(END, r' \coprod_a^b x ')).place(x=518, y=45, width=26, height=26)
        self.i4_14 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((326, 100, 350, 124)))
        Button(self.b_tab, image=self.i4_14, command=lambda: self.textbox.insert(END, r' \bigcup_a^b x ')).place(x=561, y=45, width=26, height=26)
        self.i4_15 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((351, 100, 375, 124)))
        Button(self.b_tab, image=self.i4_15, command=lambda: self.textbox.insert(END, r' \bigwedge_a^b x ')).place(x=604, y=45, width=26, height=26)
        self.i4_16 = ImageTk.PhotoImage(Img.open('equation_textures.png').crop((377, 100, 400, 124)))
        Button(self.b_tab, image=self.i4_16, command=lambda: self.textbox.insert(END, r' \bigoplus ')).place(x=647, y=45, width=26, height=26)

    def transform(self):
        geometry_options = {"tmargin": "1cm", "lmargin": "1cm"}
        doc = Document(geometry_options=geometry_options)
        with doc.create(Alignat(numbering=False, escape=False)) as agn:
            agn.append(self.textbox.get(0.0, END))
        doc.generate_pdf('equation', clean_tex=False)


if __name__ == '__main__':
    _ = Abc()
